### ISSUE TITLE
Questions: Types generator, updating types and new addon

### ISSUE THREAD

**Issue by deepflame** [draios/ember-typescript2#2]
Hi there,

thanks for providing the addon.
I am pretty new to Typescript so please bare this in mind while reading my questions here ;)

I have seen this repo before: https://github.com/wagenet/ember-typings-generator
Would that help you in generating updated types for Typescript2?

Also, would it not make sense to update the typing definitions rather than providing a new addon for Ember? I personally use  ember-cli-typescript and I think it would be great to combine effort on a single addon for typescript, no? What are your thougts around that?

Thanks
Andreas

**Comment by maerten** [comment]
Hi @deepflame,

Thanks for your questions.

This repo is intended for experimentation with TypeScript+Ember and asking for feedback/discussion. ember-cli-typescript depends on @types/ember, and @types/ember isn't taking advantage of TypeScript 2.x features which we wanted to experiment with, so it was just easier to start this experimental addon from scratch.

At some point we should merge the types back into the `@types/ember` if our approach works, however there are some things we need to figure out first:
- it not clear yet if we are doing things properly (e.g. using `interface` instead of `class`)
- we are experimenting with some (incompatible) custom tricks to get type inference from Ember patterns like `this.store.createRecord('my-user-model')` => `MyUserModel`

Ember-typings-generator looks interesting, it might help with getting a basic scaffold if its adapted to our interfaces (I think that one generates `class` interfaces with `any` types).
Here's some example output linked by @dwickern in #topic-typescript on the Ember Slack: https://github.com/dwickern/ember-types/tree/api-output/declaration-generator/out

Thanks!
Maarten

**Comment by deepflame** [comment]
Thanks for the infos Maarten!

Sounds really interesting. Good luck to you guys with the project!
